- name: "install and run nginx"
  hosts: web
  become: yes
  tasks:
  - name: "installation nginx"
    ansible.builtin.package:
      name: nginx
      state: present

  - name: "run nginx"
    ansible.builtin.package:
      name: nginx
      state: started
      enabled: yes  