- name: server and user installation
  hosts: local
  connection: local
  vars:
    city: "Hyderabad Play"
    schoolname: Kinnera
  vars_files:
  - vardetails.yaml
  vars_prompt:
  - name: city
    prompt: "city name?"
    private: false
  tasks:
  - name: print ur city
    vars:
      city: "Hyderabad task"
    ansible.builtin.debug:
      msg: " {{city}}"
      


    